FROM scratch
LABEL org.label-schema.schema-version="1.0" \
	org.label-schema.name="Ubuntu Base Image" \
	maintainer="https://leanpub.com/dockerfile Anish Nath" \
	org.label-schema.vcs-description="ubuntu Base Image-minimal" \
	org.label-schema.docker.cmd="docker run -it ubuntu sh" \
	org.label-schema.vendor="ubuntu" \
	org.label-schema.license="GPLv2" \
	org.label-schema.build-date="20190801"
ADD ubuntu-base-19.04-base-amd64.tar.gz /
CMD ["/bin/bash"]
