FROM scratch
LABEL org.label-schema.schema-version="1.0" \
	org.label-schema.name="CentOS Base Image" \
	maintainer="anish2good@yahoo.co.in" \
	org.label-schema.vcs-description="centos7 Base Image-minimal" \
	org.label-schema.docker.cmd="docker run centos7" \
	org.label-schema.vendor="CentOS" \
	org.label-schema.license="GPLv2" \
	org.label-schema.build-date="20190801"
ADD centos-7.2.1511-docker.tar.xz /
CMD ["/bin/bash"]
